export const URL_LOGIN = "/Login/login";
export const URL_REGISTER = "/Login/register";
export const URL_SEARCH = '/Rooms/searchRooms';
export const URL_SEARCH_USER = '/Rooms/getRoomsByUser';
export const URL_NEW_HOME = '/Rooms/saveNewRoom';
export const URL_CATEGORY = '/Rooms/getCategory';
export const URL_USER = '/User/getAllUser';
export const URL_USER_EDIT = '/User/editUser';
export const URL_GET_USER = '/User/getAllUser';
export const URL_EDIT = '/Rooms/editRooms';
export const URL_CREATE_CATEGORY = "/Rooms/newCategory"
export const URL_DELETE = '/Rooms/deleteRoom'
export const URL_ACTIVE = '/Rooms/activeRoom'
export const URL_GET_DETAILS = "/Rooms/getRoomById?id="
